# Algorythms NEFU

In [45]:
def getstringnarabu(a: str, p: str):
    result = ""
    if (len(a)>len(p)):
        result = "p"
        p = p.replace('p', '',1)
    while(len(a)>len(p) | len(p) != 0):
        a = a.replace('aa','',1)
        p = p.replace('p', '',1)
        result = result + "aa"
        result = result + "p"

    while(a!="" ):
        if len(p)!=0:
            result = result + 'p'
            p = p.replace('p','',1)
        result = result + 'a'
        a = a.replace('a','',1)
    print(result)
def narabu(n,m):
    ispossible = False
    if n >= m:
        a = "a"*n
        p = "p"*m
    else:
        a = "a"*m
        p = "p"*n
    if int(len(a)/2) <= (len(p)-1):
        ispossible = True
    if ispossible:
        getstringnarabu(a,p)
        return True
    else:
        return False
narabu(5,6)

paapaappapa


True

In [61]:
def beauty(a):
    p = a*4 + 2*(1+(a-1))*(a-1)/2 + 1
    print(p)
beauty(5)

41.0


In [77]:
import random
def sort(a: list):
    k = 0
    for i in range(len(a)):
        min = a[0]
        ind = 0
        for j in range(len(a)-k):
            if a[j] < min:
                ind = j
                min = a[j]
        k += 1
        g = a[ind]
        a[ind] = a[len(a)-k]
        a[len(a)-k] = g
    return a[::-1]
a = [random.randint(1,100) for i in range(30)]
print(sort(a))

[4, 7, 7, 9, 12, 15, 18, 21, 22, 23, 26, 30, 34, 35, 40, 44, 49, 52, 57, 58, 68, 70, 75, 77, 79, 83, 84, 90, 95, 100]


# Бинарный поиск

In [53]:
import random
def binarysearch(a: list, b: int) -> int:
    index_end = len(a)-1
    index_begin = 0
    index_part = int(index_end/2)
    step = 0
    while True:
        if a[index_part] == b:
            return index_part
        elif a[index_end] == b:
            return index_end
        elif a[index_begin] == b:
            return index_begin
        elif a[index_part] < b:
            print("higher", step, index_begin, index_part, index_end)
            index_begin = index_part
            index_part = int((index_end-index_part)/2+index_part)
            index_end = index_end
        elif a[index_part] > b:
            print("lower", step, index_begin, index_part, index_end)
            index_begin = index_begin
            index_end = index_part
            index_part = int(index_part-(index_part-index_begin)/2)
        step += 1
            

a = [random.randint(1,10000000) for i in range(300000)]
a.sort()
b = a[3]
binarysearch(a,b)

lower 0 0 149999 299999
lower 1 0 74999 149999
lower 2 0 37499 74999
lower 3 0 18749 37499
lower 4 0 9374 18749
lower 5 0 4687 9374
lower 6 0 2343 4687
lower 7 0 1171 2343
lower 8 0 585 1171
lower 9 0 292 585
lower 10 0 146 292
lower 11 0 73 146
lower 12 0 36 73
lower 13 0 18 36
lower 14 0 9 18
lower 15 0 4 9
higher 16 0 2 4


3

In [62]:
def binarysearch_upgraded(a: list, b: int) -> int:
    index_begin = 0
    index_end = len(a)-1
    while index_begin<=index_end:
        index_part = int((index_end+index_begin)/2)
        if a[index_part] < b:
            print("higher", index_begin, index_part, index_end)
            index_begin = index_part + 1
        elif a[index_part] > b:
            print("lower", index_begin, index_part, index_end)
            index_end = index_part - 1
        elif a[index_part] == b:
            return index_part

a = [random.randint(1,10000000) for i in range(300000)]
a.sort()
b = a[299999]
binarysearch_upgraded(a,b)

higher 0 149999 299999
higher 150000 224999 299999
higher 225000 262499 299999
higher 262500 281249 299999
higher 281250 290624 299999
higher 290625 295312 299999
higher 295313 297656 299999
higher 297657 298828 299999
higher 298829 299414 299999
higher 299415 299707 299999
higher 299708 299853 299999
higher 299854 299926 299999
higher 299927 299963 299999
higher 299964 299981 299999
higher 299982 299990 299999
higher 299991 299995 299999
higher 299996 299997 299999
higher 299998 299998 299999


299999

# 643. Maximum Average Subarray I

In [ ]:
class Solution(object):
    def findMaxAverage(self, nums: list[int], k: int) -> float:
        """
        :type nums: List[int]
        :type k: int
        :rtype: float
        """
        max = nums[0]
        n = 1.0
        for i in range(1,k):
            n += 1.0
            max += nums[i]
        avg = max/n
        for i in range(k,len(nums)):
            max += nums[i]
            max -= nums[i-k]
            if (avg < max/n):
                avg = max/n
        return avg

nums = [0,1,1,3,3]
k = 4
Solution.findMaxAverage(1,nums,k)

2.0

# 2. Add Two Numbers

In [ ]:
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def addTwoNumbers(self, l1: Optional[ListNode], l2: Optional[ListNode]) -> Optional[ListNode]:
        """
        :type head: Optional[ListNode]
        :rtype: Optional[ListNode]
        """
  
        num1 = 0
        k = 1
        l3 = l1
        l4 = l2
        l5 = l1
        l6 = l2
        l7 = 0
        k_5 = 0
        k_6 = 0
        while l5 != None:
            l5 = l5.next
            k_5 += 1
        while l6 != None:
            l6 = l6.next
            k_6 += 1
        if k_5 > k_6:
            l7 = l1
            l8 = l1
        else:
            l7 = l2
            l8 = l2
        d = 0
        dummy = ListNode(0)
        current = dummy
        while l3 != None and l4 != None:
            gg = 0
            if d == 1:
                gg = 1
                d = 0
            if l3.val+l4.val>9:
                gg += l3.val + l4.val - 10 
                l7.val = gg
                d = 1
            else:
                gg += l3.val + l4.val
                l7.val = gg
            l3 = l3.next
            l4 = l4.next
            current.next = ListNode(digit)
            l7 = l7.next
        return l7

# 3. Longest Substring Without Repeating Characters

In [ ]:
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        pass

# Algorythms NEFU

## 2.5 

In [ ]:
import random
def binarysearch(a: list, b: int, c: list) -> int:
    index_begin = 0
    index_end = len(a)-1
    while index_begin<=index_end:
        index_part = int((index_end+index_begin)/2)
        if a[index_part] < b:
            print("higher", index_begin, index_part, index_end)
            index_begin = index_part + 1
        elif a[index_part] > b:
            print("lower", index_begin, index_part, index_end)
            index_end = index_part - 1
        elif a[index_part] == b:
            return index_part, c[index_part]

a = [random.randint(1,10000000) for i in range(300000)]
a.sort()
b = a[1594]
c = [random.randint(0,1) for i in range(300000)]
binarysearch(a,b,c)

lower 0 149999 299999
lower 0 74999 149998
lower 0 37499 74998
lower 0 18749 37498
lower 0 9374 18748
lower 0 4686 9373
lower 0 2342 4685
higher 0 1170 2341
lower 1171 1756 2341
higher 1171 1463 1755
lower 1464 1609 1755
higher 1464 1536 1608
higher 1537 1572 1608
higher 1573 1590 1608
lower 1591 1599 1608


(1594, 0)

# 3 Lab tasks (Recursive functions)

## 3.4

In [28]:
def countdigits(n: int, count = 1) -> tuple[int, int]:
    if n < 10:
        print(n,count)
        return n,count
    n /= 10
    count += 1
    countdigits(n,count)
countdigits(1032)

1.032 4


## 3.5

In [41]:
def powerize(base: int | float, exponent: int, multiplied = 1) -> int | float:
    if (exponent == 0):
        print(multiplied)
        return multiplied
    multiplied *= base
    exponent -= 1
    powerize(base,exponent, multiplied)
powerize(2,10)

1024


## 3.6 Hanoy tower

## 3.1, 3.2, 3.3

3.1. 1. ukazhu, 2. 84. 3. 
3.2 
3.3 1. ukazhu 2. 6 3.

# 3.7 Palyndrome

In [123]:
def palyndrome(s: str) -> bool:
    if s[0] != s[-1]:
        print('False')
        return False
    elif (len(s) == 1) or (len(s)==2 and s[0] == s[-1]):
        print('True')
        return True
    else:
        s = s[1:(len(s)-1)]
        print(s)
        palyndrome(s)
palyndrome("abbccbba")

bbccbb
bccb
cc
True


# 3.8 %10

In [124]:
def desyatki(number: int, count = 0) -> int:
    if number == 0:
        return count
    elif number%10==0:
        number = number//10
        count += 1
    else:
        number = number//10
    print(count)
    desyatki(number,count)
print(desyatki(1000111001))

0
1
2
2
2
2
3
4
5
5
None


# 3.9 

In [132]:
def razbienie(n: int, count = 0, razb = []):
    if count == 0:
        for i in range(n):
            razb.append(1)
        count += 1
        print(razb)
        razbienie(n, count, razb)
    else:
        if len(razb) == 1 or razb[0] == n:
            return 1
        if razb[-1] == 1:
            razb[-2] += razb[-1]
            razb = razb[:len(razb)-1]
        else:
            razb[-1] -= 1
            razb[-2] += razb[-1]
        count += 1
        razb.sort(reverse = True)
        print(razb)
        razbienie(n,count, razb)
razbienie(4)

[1, 1, 1, 1]
[2, 1, 1]
[2, 2]
[3, 1]
[4]


# 4.11-16

In [133]:
import numpy as np
vector = np.arange(12,43)
vector

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [127]:
vector = np.zeros(12)
vector[5] = 1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [128]:
matrix = np.array(([0,1,2], [3,4,5], [6,7,8]))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
vector = np.array([1,2,0,0,4,0])
vector = np.where(vector>0, 1,vector)
vector

array([1, 1, 0, 0, 1, 0])

In [130]:
matrix_1 = np.array(([1,1,1], [1,1,1], [1,1,1],[1,1,1],[1,1,1]))
matrix_2 = np.array(([2,2], [2,2], [2,2]))
matrix_3 = np.dot(matrix_1, matrix_2)
matrix_3

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [131]:
matrix = np.ones((10,10))
matrix[0,:] = 0
matrix[-1,:] = 0
matrix[:, 0] = 0
matrix[:, -1] = 0
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# laba 4

In [ ]:
#1
def counter(numbers: list, number: int) -> int:
    k = 0
    for i in range(len(numbers)):
        if number == numbers[i]:
            k += 1
    return k
counter([1,2,3,1,1],1)

3

In [2]:
#2
def second(numbers: list) -> int:
    max_num = max(numbers)
    numbers.remove(max_num)
    second_max = max(numbers)
    return second_max
second([1,1,2,3,99])

3

In [3]:
#3
def slicer(numbers: list) -> list:
    min_num = min(numbers)
    index = 0
    for i in range(len(numbers)):
        if min_num == numbers[i]:
            index = i
    numbers_2 = numbers[index:]
    max_2 = max(numbers_2)
    numbers.remove(max_2)
    return numbers
slicer([1,2,3,3,4,0,9,9,10,1])

[1, 2, 3, 3, 4, 0, 9, 9, 1]

In [12]:
#4
def righter(numbers: list, k: int) -> list:
    left_num = numbers[-k:]
    right_num = numbers[:-k]
    numbers = left_num + right_num
    return numbers
righter([1,2,3,4,5,6,7,8],4)

[5, 6, 7, 8, 1, 2, 3, 4]

In [ ]:
#5
import numpy as np

def matrix_quad(n: int) -> np.array:
    matrix = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if (i==j):
                matrix[i,j] = 1
            elif (i>j):
                matrix[i,j] = 2
            elif (i<j):
                matrix[i,j] = 0
    return matrix.T
matrix_quad(6)

array([[1., 2., 2., 2., 2., 2.],
       [0., 1., 2., 2., 2., 2.],
       [0., 0., 1., 2., 2., 2.],
       [0., 0., 0., 1., 2., 2.],
       [0., 0., 0., 0., 1., 2.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
#6
def symmetric(matrix: np.array) -> bool:
    if np.array_equal(matrix, matrix.T):
        return True
    else:
        return False
print(symmetric(np.zeros((4,4))))
print(symmetric(np.array(([1,2,2],[2,1,2],[2,2,1]))))
print(symmetric(np.array(([1,2,2],[2,1,2],[2,3,1]))))

True
True
False


In [ ]:
#7
def counts_options(board: np.array) -> int:
    pass

In [33]:
#8
def snake_straight(n: int, m: int) -> np.array:
    snake = np.zeros((n,m))
    k = 0
    for i in range(n):
        for j in range(m):
            if(i%2==0):
                snake[i,j] = k
            else:
                snake[i,-j] = k
            k += 1
    return snake
snake_straight(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  9.,  8.,  7.,  6.],
       [10., 11., 12., 13., 14.],
       [15., 19., 18., 17., 16.],
       [20., 21., 22., 23., 24.]])

In [8]:
import numpy as np
def snake(n: int, m: int):
    A = np.zeros((2,10))
    x = 0
    for i in range(n):
        if i % 2 == 0:             
            for j in range(m):
                A[i][j] = x
                x += 1
        else:                
            for j in range(m - 1, -1, -1):
                A[i][j] = x
                x += 1

    for row in A:
        print(*row)
snake(2,10)

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0
19.0 18.0 17.0 16.0 15.0 14.0 13.0 12.0 11.0 10.0
